<div id="footer">
    <div id="footer-content"><div class='wsite-elements wsite-footer'>
            <div><div class="wsite-multicol"><div class="wsite-multicol-table-wrap" style="margin:0 -15px;">
                        <table class="wsite-multicol-table">
                            <tbody class="wsite-multicol-tbody">
                            <tr class="wsite-multicol-tr">
                                <td class="wsite-multicol-col" style="width:49.981634312238%; padding:0 15px;">



                                    <div style="text-align:left;"><div style="height:10px;overflow:hidden"></div>
                                        <span class="wsite-social wsite-social-default"><a class='first-child wsite-social-item wsite-social-facebook' href='https://www.facebook.com/campuselect' target='_blank'><span class='wsite-social-item-inner'></span></a><a class='wsite-social-item wsite-social-twitter' href='https://twitter.com/CampusElect' target='_blank'><span class='wsite-social-item-inner'></span></a><a class='last-child wsite-social-item wsite-social-mail' href='mailto:info@campuselect.org' target='_blank'><span class='wsite-social-item-inner'></span></a></span>
                                        <div style="height:10px;overflow:hidden"></div></div>

                                    <div class="paragraph" style="text-align:left;"><font size="2">&copy; Campus Election Engagement Project 2015.&nbsp;</font><span style="font-size: small; line-height: 15.199999809265137px;">All rights reserved.</span><br /><br /><font size="2"><strong>West Coast Office:</strong></font><br /><font size="2"><span style="text-align: center;">3232 41</span>st<span style="text-align: center;"> Ave SW&nbsp;</span><br />Seattle, WA 98116</font><br /><br /><font size="2"><strong>East Coast Office:</strong></font><br /><font size="2">615 N. Pearl Street</font><br /><font size="2">Granville, OH 43023<br /></font><span style=""></span><br /><font size="5"><strong>For more information and resources contact us <a href="mailto:theresa@campuselect.org" title="">here.&nbsp;</a></strong></font><br /><br /><br /><span style=""></span></div>



                                </td>				<td class="wsite-multicol-col" style="width:50.018365687762%; padding:0 15px;">



                                    <h2 class="wsite-content-title" style="text-align:left;"><font color="#a82e2e">Support CEEP</font></h2>
                                    <div class="paragraph" style="text-align:left;display:block;"><font color="#818181">We're raising funds for our 2016 work and beyond. Please visit our&nbsp;<strong><a href="http://www.campuselect.org/donate.html"><span id="selectionBoundary_1413919440995_00018465425819158554">&#65279;</span>DONATE<span id="selectionBoundary_1413919440995_8371915596071631">&#65279;</span></a></strong>&nbsp;page to contribute &mdash; every dollar helps!&nbsp;</font></div>

                                    <div class="wsite-spacer" style="height:50px;"></div>

                                    <div><div class="wsite-image wsite-image-border-none " style="padding-top:10px;padding-bottom:10px;margin-left:0;margin-right:0;text-align:center">
                                            <a>
                                                <img src="882713_orig.png" alt="Picture" style="width:100%;max-width:500px" />
                                            </a>
                                            <div style="display:block;font-size:90%"></div>
                                        </div></div>



                                </td>			</tr>
                            </tbody>
                        </table>
                    </div></div></div></div>
        <script type='text/javascript'>
            //<!--

            if (document.cookie.match(/(^|;)\s*is_mobile=1/)) {
                var windowHref = window.location.href || '';
                if (windowHref.indexOf('?') > -1) {
                    windowHref += '&';
                } else {
                    windowHref += '?';
                }
                document.write(
                    "&nbsp;&nbsp;&nbsp;&nbsp;" +
                    "<a class='wsite-view-link-mobile' href='" + windowHref + "view=mobile'>Mobile Site</a>"
                );
            }

            //-->
        </script></div>
</div>
</div>

<a href="https://plus.google.com/101465898100981394675" rel="publisher">Google+</a><script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-7870337-1']);
    _gaq.push(['_setDomainName', 'none']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

<!-- Quantcast Tag -->
<script type="text/javascript">
    var _qevents = _qevents || [];

    (function() {
        var elem = document.createElement('script');
        elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";
        elem.async = true;
        elem.type = "text/javascript";
        var scpt = document.getElementsByTagName('script')[0];
        scpt.parentNode.insertBefore(elem, scpt);
    })();

    _qevents.push({
        qacct:"p-0dYLvhSGGqUWo",
        labels:"l10,u11680869.u11680869s729139342179837495"
    });
</script>

<noscript>
    <div style="display:none;">
        <img src="//pixel.quantserve.com/pixel/p-0dYLvhSGGqUWo.gif?labels=l10,u11680869.u11680869s729139342179837495" border="0" height="1" width="1" alt="Quantcast"/>
    </div>
</noscript>
<!-- End Quantcast tag -->


<script>

    (function(jQuery) {
        try {
            if (jQuery) {
                jQuery('div.blog-social div.fb-like').attr('class', 'blog-social-item blog-fb-like');
                var $commentFrame = jQuery('#commentArea iframe');
                if ($commentFrame.length > 0) {
                    var frameHeight = jQuery($commentFrame[0].contentWindow.document).height() + 50;
                    $commentFrame.css('min-height', frameHeight + 'px');
                }
                if (jQuery('.product-button').length > 0){
                    jQuery(document).ready(function(){
                        jQuery('.product-button').parent().each(function(index, product){
                            if(jQuery(product).attr('target') == 'paypal'){
                                if (!jQuery(product).find('> [name="bn"]').length){
                                    jQuery('<input>').attr({
                                        type: 'hidden',
                                        name: 'bn',
                                        value: 'DragAndDropBuil_SP_EC'
                                    }).appendTo(product);
                                }
                            }
                        });
                    });
                }
            }
            else {
                // Prototype
                $$('div.blog-social div.fb-like').each(function(div) {
                    div.className = 'blog-social-item blog-fb-like';
                });
                $$('#commentArea iframe').each(function(iframe) {
                    iframe.style.minHeight = '410px';
                });
            }
        }
        catch(ex) {}
    })(window._W && _W.jQuery);

</script>
<div id="eu-cookie" class="notification" style="display: none;">
    <span id="eu-cookie-content"></span>
    <span id="eu-cookie-close">&#10005</span>
</div>

<script type="text/javascript">
    (function($) {
        var cookie_location = '';

        // this cookie_content should already be pre-encoded from CookieSettingView.js
        var cookie_content = '' || _W.stl('templates.publish.virtual-includes.footerCode_1');

        if (!_W.getCookie('729139342179837495_cookie_policy') || (_W.getCookie('729139342179837495_cookie_policy') !== cookie_content)){
            if (cookie_location === 'top' || cookie_location === 'bottom'){
                $('#eu-cookie-content').text(decodeURIComponent(cookie_content));
                (cookie_location === 'top') ? animateFromTop() : animateFromBottom();
                $('#eu-cookie').show();
            }
        }

        $('#eu-cookie-close').click(function(){
            _W.setCookie('729139342179837495_cookie_policy', cookie_content, 100000);
            $('#eu-cookie').hide();
        });

        function animateFromTop(){
            $('#eu-cookie').css({
                'top': '0px',
                'animation': 'reveal-top 1 2s'
            });
        }

        function animateFromBottom(){
            $('#eu-cookie').css({
                'bottom': '0px',
                'animation': 'reveal-bottom 1 2s'
            });
        }
    })(window._W && _W.jQuery);

</script>