
	<div class="bg-wrapper">
		<div id="header">
			<div id="sitename"><span class="wsite-logo">

	<a href="/">
		<img src="1413918722.png" style="margin-left:5px;" />
	</a>

</span></div>
		</div>
		<div id="navigation"><ul class="wsite-menu-default">
		<li id="active" class="wsite-menu-item-wrap">
			<a
					href="/"
				class="wsite-menu-item"
				>
				Home
			</a>

		</li>
		<li id="pg914917180186124003" class="wsite-menu-item-wrap">
			<a
					href="/engagement-resources.html"
				class="wsite-menu-item"
				>
				Engagement Resources
			</a>
			<div class="wsite-menu-wrap" style="display:none">
	<ul class="wsite-menu">
		<li id="wsite-nav-968583291270077195"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="http://ceepdev.weebly.com/engagement-resources.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			CEEP Resources
		</span><span class="wsite-menu-arrow">&gt;</span>
	</a>
	<div class="wsite-menu-wrap" style="display:none">
	<ul class="wsite-menu">
		<li id="wsite-nav-919845591354362238"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/seven-key-ways.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Seven Key Ways
		</span>
	</a>

</li>
<li id="wsite-nav-503284036987563423"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/campus-electoral-engagement-assessment.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Campus Electoral Engagement Assessment
		</span>
	</a>

</li>
<li id="wsite-nav-401553581590275033"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/combatting-cynicism.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Combatting Cynicism
		</span>
	</a>

</li>
<li id="wsite-nav-607821028859605664"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/covering-elections-through-social-media.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Covering Elections Through Social Media
		</span>
	</a>

</li>
<li id="wsite-nav-958533759235014999"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/working-with-student-newspapers.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Working With Student Newspapers
		</span>
	</a>

</li>

	</ul>
</div>

</li>
<li id="wsite-nav-611977428648938041"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/nonpartisan-voter-guides.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Nonpartisan Voter Guides
		</span>
	</a>

</li>
<li id="wsite-nav-624545431122091246"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/online-voter-tools.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Online Voter Tools
		</span>
	</a>

</li>
<li id="wsite-nav-262237840347589159"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/voter-registration-resources.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Voter Registration Resources
		</span>
	</a>

</li>
<li id="wsite-nav-364029882193842793"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/voter-education-resources.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Voter Education Resources
		</span>
	</a>

</li>
<li id="wsite-nav-954206517908024388"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/voter-engagement-orgs.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Voter Engagement Orgs
		</span>
	</a>

</li>

	</ul>
</div>

		</li>
		<li id="pg558305700226712463" class="wsite-menu-item-wrap">
			<a
					href="/about-ceep.html"
				class="wsite-menu-item"
				>
				About CEEP
			</a>
			<div class="wsite-menu-wrap" style="display:none">
	<ul class="wsite-menu">
		<li id="wsite-nav-351546915248872466"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/staff.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Staff
		</span>
	</a>

</li>
<li id="wsite-nav-863102434851076586"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/partners--allies.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Partners & Allies
		</span>
	</a>

</li>
<li id="wsite-nav-626627073209250890"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/ceep-advisory-board.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			CEEP Advisory Board
		</span>
	</a>

</li>
<li id="wsite-nav-309074309712261822"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/contact-information.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Contact Information
		</span>
	</a>

</li>

	</ul>
</div>

		</li>
		<li id="pg461008184701594257" class="wsite-menu-item-wrap">
			<a
					href="/successes.html"
				class="wsite-menu-item"
				>
				Successes
			</a>
			<div class="wsite-menu-wrap" style="display:none">
	<ul class="wsite-menu">
		<li id="wsite-nav-856378520631882964"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/select-2014-state-successes.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Select 2014 State Successes
		</span>
	</a>

</li>
<li id="wsite-nav-692526198764553184"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/select-2012-state-successes.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Select 2012 State Successes
		</span><span class="wsite-menu-arrow">&gt;</span>
	</a>
	<div class="wsite-menu-wrap" style="display:none">
	<ul class="wsite-menu">
		<li id="wsite-nav-770716930843652037"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/colorado-nevada--new-mexico.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Colorado, Nevada,  & New Mexico
		</span>
	</a>

</li>
<li id="wsite-nav-261248678127382066"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/florida1.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Florida
		</span>
	</a>

</li>
<li id="wsite-nav-462538568257397840"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/indiana.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Indiana
		</span>
	</a>

</li>
<li id="wsite-nav-569839546402360212"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/iowa.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Iowa
		</span>
	</a>

</li>
<li id="wsite-nav-983292519829647638"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/massachusetts.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Massachusetts
		</span>
	</a>

</li>
<li id="wsite-nav-565858158822147282"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/michigan1.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Michigan
		</span>
	</a>

</li>
<li id="wsite-nav-725807686176038434"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/montana.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Montana
		</span>
	</a>

</li>
<li id="wsite-nav-754492914560367883"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/north-carolina1.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			North Carolina
		</span>
	</a>

</li>
<li id="wsite-nav-107636510260416405"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/ohio1.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Ohio
		</span>
	</a>

</li>
<li id="wsite-nav-538067518488040433"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/pennsylvania.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Pennsylvania
		</span>
	</a>

</li>
<li id="wsite-nav-775842722264869753"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/virginia1.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Virginia
		</span>
	</a>

</li>
<li id="wsite-nav-141817888514803215"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/washington-state.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Washington State
		</span>
	</a>

</li>
<li id="wsite-nav-671482740941060493"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/wisconsin.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Wisconsin
		</span>
	</a>

</li>
<li id="wsite-nav-753869217229880992"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/tx-mo-nh-mn-nd-az-ky-ri-and-ne.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			TX, MO, NH, MN, ND, AZ, KY, RI, and NE
		</span>
	</a>

</li>

	</ul>
</div>

</li>
<li id="wsite-nav-247254566779585814"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/-select-2008-state-successes.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			 Select 2008 State Successes
		</span><span class="wsite-menu-arrow">&gt;</span>
	</a>
	<div class="wsite-menu-wrap" style="display:none">
	<ul class="wsite-menu">
		<li id="wsite-nav-695458430636593473"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/colorado.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Colorado
		</span>
	</a>

</li>
<li id="wsite-nav-887036261439190472"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/florida.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Florida
		</span>
	</a>

</li>
<li id="wsite-nav-893798524541529628"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/indiana1.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Indiana
		</span>
	</a>

</li>
<li id="wsite-nav-299987967458118312"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/michigan.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Michigan
		</span>
	</a>

</li>
<li id="wsite-nav-970219995510354302"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/minnesota.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Minnesota
		</span>
	</a>

</li>
<li id="wsite-nav-309487643988734761"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/north-carolina.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			North Carolina
		</span>
	</a>

</li>
<li id="wsite-nav-482734610448116967"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/ohio.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Ohio
		</span>
	</a>

</li>
<li id="wsite-nav-190902766585227253"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/oregon.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Oregon
		</span>
	</a>

</li>
<li id="wsite-nav-724692198699669128"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/virginia.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Virginia
		</span>
	</a>

</li>
<li id="wsite-nav-862475995801905480"
	class="wsite-menu-subitem-wrap "
	>
	<a
			href="/mississippi-nevada-new-mexico--pennsylvania.html"
		class="wsite-menu-subitem"
		>
		<span class="wsite-menu-title">
			Mississippi, Nevada, New Mexico, & Pennsylvania
		</span>
	</a>

</li>

	</ul>
</div>

</li>

	</ul>
</div>

		</li>
		<li id="pg692110294242545514" class="wsite-menu-item-wrap">
			<a
					href="/donate.html"
				class="wsite-menu-item"
				>
				Donate
			</a>

		</li>
		<li id="pg321005297354341082" class="wsite-menu-item-wrap">
			<a
					href="/employment.html"
				class="wsite-menu-item"
				>
				Employment
			</a>

		</li>
		<li id="pg777395629937396054" class="wsite-menu-item-wrap">
			<a
					href="/staff-blog.html"
				class="wsite-menu-item"
				>
				Staff Blog
			</a>

		</li>
		<li id="pg271786550179676746" class="wsite-menu-item-wrap">
			<a
					href="/activity-tracker.html"
				class="wsite-menu-item"
				>
				Activity Tracker
			</a>

		</li>
</ul>
</div>

		<div id="content-wrapper">
			<div id="content"><div id='wsite-content' class='wsite-elements wsite-not-footer'>
<div class="wsite-search-element-outer"><div class="wsite-search-element-align-right" style="padding: 0 0 0 0">
  <form class="wsite-search-element-form" action="/apps/search" method="get">
    <div class="wsite-search-element">
      <input class="wsite-input wsite-search-element-input" type="text" name="q" placeholder="Search" autocomplete="off" />
      <span class="wsite-search-element-submit" title="Search"></span>
    </div>
  </form>
</div></div>